"use client";

import Link from "next/link";
import { useStore } from "./store-provider";
import { BrandMark, Icon } from "./icons";

export function About() {
  const { t } = useStore();
  return <main className="about-page"><div className="breadcrumbs page-gutter"><Link href="/">{t("Home", "হোম")}</Link><span>/</span><span>{t("Our story", "আমাদের গল্প")}</span></div><section className="about-hero page-gutter"><div className="about-photo reveal"><img src="/images/founder.jpg" alt="An editorial portrait inspired by the warmth of the Satrang atelier" /><span>{t("A BRAND WITH A HEART. A STORY WITH COLOUR.", "হৃদয়ের একটি ব্র্যান্ড। রঙের একটি গল্প।")}</span></div><div className="about-intro reveal"><p className="eyebrow">{t("OUR ROOTS. OUR RANG.", "আমাদের শিকড়। আমাদের রঙ।")}</p><h1>{t("Seven colours.", "সাতটি রঙ।")}<br /><em>{t("One beautiful story.", "একটি সুন্দর গল্প।")}</em></h1><div className="min-h-[250px]" data-biography-placeholder aria-hidden="true" /></div></section><section className="about-manifesto page-gutter reveal"><BrandMark size={63} /><p className="eyebrow">{t("MORE THAN WHAT WE MAKE", "পোশাকের চেয়েও বেশি")}</p><h2>{t("We’re not here to dress everyone the same.", "সবাইকে একই রঙে রাঙাতে আসিনি।")}<br /><em>{t("We’re here to celebrate what makes you, you.", "এসেছি আপনার নিজের রঙকে উদ্‌যাপন করতে।")}</em></h2></section><section className="about-values page-gutter">{[{ icon: "thread" as const, number: "01", title: "Hands, not factories.", titleBn: "হাতের যত্নে গড়া।", text: "Our small-batch approach leaves room for the human touch. Thoughtful details, soft natural fabrics, and a little love in every seam.", textBn: "ছোট ছোট আয়োজনে হাতের যত্নে তৈরি হয় আমাদের পোশাক। প্রতিটি সেলাইয়ে থাকে একটু ভালোবাসা।" }, { icon: "flower" as const, number: "02", title: "Perfectly one of a kind.", titleBn: "প্রতিটি পোশাকই অনন্য।", text: "Tie-dye doesn’t follow the same path twice. The variations in each piece aren’t imperfections — they’re the beautiful part.", textBn: "টাই-ডাইয়ে একই নকশা দুবার হয় না। প্রতিটি পোশাকের আলাদা রঙ আর নকশাই তার সৌন্দর্য।" }, { icon: "leaf" as const, number: "03", title: "Rooted, not standing still.", titleBn: "শিকড়ে থেকেও নতুন।", text: "South Asian heritage is our starting point, not our limit. We carry traditional silhouettes into a fresh, expressive everyday wardrobe.", textBn: "দক্ষিণ এশিয়ার ঐতিহ্য আমাদের শুরুর স্থান। সেই ঐতিহ্যকে আমরা নতুন রূপে নিয়ে আসি প্রতিদিনের পোশাকে।" }].map((value) => <article className="reveal" key={value.number}><div><Icon name={value.icon} size={37} /><span>{value.number}</span></div><h3>{t(value.title, value.titleBn)}</h3><p>{t(value.text, value.textBn)}</p></article>)}</section><section className="about-closing page-gutter reveal"><h2>{t("Now, find your colour.", "এবার, আপনার রঙ খুঁজুন।")}</h2><p>{t("A little heritage. A little joy. A whole lot of you.", "একটু ঐতিহ্য। একটু আনন্দ। অনেকটা আপনি।")}</p><Link href="/shop" className="button button-black">{t("Explore the collection", "কালেকশন দেখুন")}<Icon name="arrow-up" size={18} /></Link></section></main>;
}
