"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import type { Product } from "@/lib/catalog";
import { BrandMark, Icon, Sparkle } from "./icons";
import { useStore } from "./store-provider";
import { CategoryCards } from "./category-cards";
import { ProductCard } from "./product-card";

export function Home({ products }: { products: Product[] }) {
  const { t } = useStore();
  const [activeTab, setActiveTab] = useState("bestsellers");
  const visualRef = useRef<HTMLDivElement>(null);
  const featured = activeTab === "bestsellers" ? products.slice(0, 4) : [products[1], products[4], products[6], products[2]].filter(Boolean);
  useEffect(() => {
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    let frame = 0;
    const scroll = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => visualRef.current?.style.setProperty("--parallax", `${Math.min(window.scrollY * 0.08, 55)}px`)); };
    window.addEventListener("scroll", scroll, { passive: true });
    return () => { cancelAnimationFrame(frame); window.removeEventListener("scroll", scroll); };
  }, []);

  return <main>
    <section className="hero-section" aria-labelledby="hero-heading"><div className="hero-visual" ref={visualRef}><img className="hero-image" src="/images/satrang-hero.jpg" alt="South Asian woman in a flowing pink and saffron tie-dye lehenga, with a billowing dupatta" loading="eager" fetchPriority="high" /></div><div className="hero-blend" /><div className="hero-copy"><p className="hero-eyebrow"><span className="little-line" />{t("COLOUR IS A WAY OF LIFE", "রঙই জীবনের গল্প")}</p><p className="hero-bangla">{t("রঙে রঙে, নিজের মতো।", "রঙে রঙে, নিজের মতো।")}</p><h1 id="hero-heading">{t("Wear your", "আপনার রঙে")}<br /><em>{t("true colours.", "নিজেকে রাঙান।")}</em></h1><p className="hero-description">{t("Rooted in heritage. Reimagined for you.", "ঐতিহ্যের শিকড়ে। আপনার জন্য নতুন করে।")}<br />{t("Handcrafted pieces, as one-of-a-kind as you are.", "হাতে গড়া প্রতিটি পোশাক, আপনার মতোই অনন্য।")}</p><div className="hero-actions"><Link href="/shop" className="button button-black ripple-button">{t("Explore the collection", "কালেকশন দেখুন")}<Icon name="arrow-up" size={18} /></Link><Link href="/about" className="hero-story-link">{t("The Satrang story", "সাত রঙের গল্প")}<Icon name="arrow" size={16} /></Link></div><div className="hero-bottom-note"><span className="note-number">01</span><span>{t("SEVEN COLOURS. ENDLESS WAYS TO BE YOU.", "সাত রঙ। নিজেকে প্রকাশের অগণিত উপায়।")}</span></div></div><div className="craft-stamp"><span>{t("SMALL BATCHES", "অল্প করে তৈরি")}</span><BrandMark size={31} /><span>{t("BIG FEELINGS", "অনেক ভালোবাসায়")}</span></div><Sparkle className="hero-sparkle" size={56} /><Link href="/product/rong-tie-dye-lehenga" className="hero-look"><span>{t("THE RONG EDIT", "রঙ কালেকশন")}</span><strong>{t("A little joy. A little twirl.", "একটু আনন্দ। একটু নাচ।")}</strong><span className="shop-look">{t("Shop the look", "এই পোশাক দেখুন")}<Icon name="arrow-up" size={14} /></span></Link><a href="#collections" className="scroll-hint" aria-label="Scroll to collections"><span>{t("SCROLL TO DISCOVER", "আরও দেখতে স্ক্রল করুন")}</span><Icon name="arrow" size={17} /></a></section>
    <div className="colour-marquee" aria-hidden="true"><div>{Array.from({ length: 3 }, (_, i) => <span className="marquee-set" key={i}><span>{t("HAND-DYED WITH LOVE", "ভালোবাসায় হাতে রাঙানো")}</span><BrandMark size={23} /><span>{t("ROOTED IN HERITAGE", "ঐতিহ্যের শিকড়ে")}</span><BrandMark size={23} /><span>{t("MADE TO BE YOU", "আপনার মতোই অনন্য")}</span><BrandMark size={23} /></span>)}</div></div>
    <section className="collection-section page-gutter" id="collections"><div className="section-heading reveal"><div><p className="eyebrow">{t("SEVEN COLOURS. ENDLESS POSSIBILITIES.", "সাত রঙ। অসীম সম্ভাবনা।")}</p><h2>{t("Find your kind of colour.", "আপনার প্রিয় রঙ খুঁজুন।")}</h2></div><Link href="/shop" className="text-link">{t("Shop all collections", "সব কালেকশন দেখুন")}<Icon name="arrow-up" size={17} /></Link></div><CategoryCards /></section>
    <section className="favourites-section page-gutter"><div className="section-heading reveal"><div><p className="eyebrow">{t("A LITTLE LOVE AT FIRST SIGHT", "প্রথম দেখায় একটু ভালোবাসা")}</p><h2>{t("Meet your new favourites.", "আপনার নতুন প্রিয় পোশাক।")}</h2></div><Link href="/shop" className="text-link">{t("View all pieces", "সব পোশাক দেখুন")}<Icon name="arrow-up" size={17} /></Link></div><div className="product-tabs" role="tablist" aria-label="Featured collection"><button role="tab" aria-selected={activeTab === "bestsellers"} className={activeTab === "bestsellers" ? "active" : ""} onClick={() => setActiveTab("bestsellers")}>{t("The best-loved", "সবচেয়ে প্রিয়")}</button><button role="tab" aria-selected={activeTab === "new"} className={activeTab === "new" ? "active" : ""} onClick={() => setActiveTab("new")}>{t("Fresh colours", "নতুন রঙ")}</button><span>{t("Small batches. Made with big love.", "অল্প করে তৈরি। অনেক ভালোবাসায়।")}</span></div><div className="home-product-grid" role="tabpanel" key={activeTab}>{featured.map((product, index) => <ProductCard key={product.id} product={product} index={index} />)}</div></section>
    <section className="values-strip page-gutter"><div><Icon name="thread" size={30} /><span><strong>{t("Made by hand, not by the hundred", "হাতে গড়া, ভালোবাসায় তৈরি")}</strong><small>{t("Thoughtful pieces. Small, intentional batches.", "যত্নে গড়া পোশাক। ছোট ছোট আয়োজন।")}</small></span></div><div><Icon name="flower" size={33} /><span><strong>{t("No two colours tell the same story", "প্রতিটি রঙের আলাদা গল্প")}</strong><small>{t("Your tie-dye is as unique as you are.", "আপনার মতোই আপনার টাই-ডাইও অনন্য।")}</small></span></div><div><Icon name="leaf" size={30} /><span><strong>{t("A little kinder. A little slower.", "একটু যত্নে। একটু ধীরে।")}</strong><small>{t("Natural fabrics, made to be loved for longer.", "প্রাকৃতিক কাপড়, দীর্ঘদিন ভালোবাসার জন্য।")}</small></span></div></section>
    <section className="home-story page-gutter"><div className="story-image reveal"><img src="/images/founder.jpg" alt="An editorial portrait inspired by Satrang’s founder and warm artisan atelier" loading="lazy" /><span>{t("THE HEART BEHIND THE COLOURS", "রঙের পেছনের ভালোবাসা")}</span></div><div className="story-copy reveal"><p className="eyebrow">{t("OUR ROOTS. OUR RANG.", "আমাদের শিকড়। আমাদের রঙ।")}</p><h2>{t("Seven colours.", "সাতটি রঙ।")}<br /><em>{t("One beautiful story.", "একটি সুন্দর গল্প।")}</em></h2><div className="min-h-[80px]" data-biography-placeholder aria-hidden="true" /><p>{t("We believe what you wear should feel like who you are. Joyful, rooted, and beautifully your own.", "আমরা বিশ্বাস করি, আপনার পোশাকেও থাকুক আপনার নিজস্বতা। আনন্দে, ঐতিহ্যে আর নিজের রঙে।")}</p><Link href="/about" className="button button-outline">{t("Get to know Satrang", "সাত রঙকে জানুন")}<Icon name="arrow-up" size={17} /></Link></div></section>
  </main>;
}
